[mongodb]
username = "premiumgroup"
password = "VitorOMelhorKkk1306"
cluster = "businessoperationsrevie.zxb4sgn.mongodb.net"
database = "BusinessOperationReview"

uri = "mongodb+srv://premiumgroup:VitorOMelhorKkk1306@businessoperationsrevie.zxb4sgn.mongodb.net/?retryWrites=true&w=majority&tls=true&tlsAllowInvalidCertificates=false"